<?php
// @codingStandardsIgnoreFile
?>
<?php $viewModel = $block->getCustomProductLayerViewModel();?>
<?php $viewModel->setAttributeId($block->getAttributeId());?>
<?php $attributeId = $viewModel->getAttributeId()?>
<?php $isMulti = $viewModel->getIsMultiselect()?>
<?php $canShowQty = $this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer();?>
<ol class="items" id="<?= $attributeId ?>_items" >
    <?php foreach ($filterItems as $filterItem): ?>
        <?php $requestVar = $filterItem->getFilter()->getRequestVar();?>
        <?php $filterItemVal = is_array($filterItem->getValue()) ? implode('-', $filterItem->getValue()) : $filterItem->getValue()?>
        <?php $dataOptPath = ($requestVar != 'cat') ? $filterItem->getFilter()->getAttributeModel()->getAttributeCode() . '='. $filterItemVal : 'cat='.$filterItemVal;?>
        <li class="item" id="wp_ln_attr_<?= $attributeId ?>_<?= /* @escapeNotVerified */ is_array($filterItem->getValue()) ? implode('-', $filterItem->getValue()) : $filterItem->getValue() ?>">
            <?php if ($filterItem->getCount() > 0): $filter = $filterItem->getFilter();?>
                <a href="<?= $block->escapeUrl($filterItem->getUrl()) ?>"
                   data-opt-path="<?= /* @escapeNotVerified */ $block->escapeHtmlAttr($dataOptPath) ?>"
                   data-is-multi="<?= $isMulti?>">
                    <?php echo $isMulti ? '<input type="checkbox" class="rm_checkbox">' : ''; ?>
                    <?= /* @escapeNotVerified */ $filterItem->getLabel() ?>
                    <?php if ($canShowQty): ?>
                        <span class="count"><?= /* @escapeNotVerified */ $filterItem->getCount() ?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1):?> <?= /* @escapeNotVerified */ __('item') ?><?php else:?> <?= /* @escapeNotVerified */ __('items') ?><?php endif;?></span></span>
                    <?php endif; ?>
                </a>
            <?php else:?>
                <?= /* @escapeNotVerified */ $filterItem->getLabel() ?>
                <?php if ($canShowQty): ?>
                    <span class="count"><?= /* @escapeNotVerified */ $filterItem->getCount() ?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1):?><?= /* @escapeNotVerified */ __('item') ?><?php else:?><?= /* @escapeNotVerified */ __('items') ?><?php endif;?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
