<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block RedMonks\ImprovedLayeredNavigation\Block\Navigation
 */
$isAjaxMode = $block->isAjaxMode();
$jsClass = ($isAjaxMode) ? 'RedMonks_ImprovedLayeredNavigation/js/product/list/toolbar' : false;
?>
<div class="wp-filters <?php if ($isAjaxMode) echo 'wp-filters-ajax' ?>"></div>
<?php if ($block->canShowBlock()): ?>
    <div class="block filter" id="layered-filter-block"
         data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?= /* @escapeNotVerified */
        $filtered ?>">
            <strong data-role="title"><?= /* @escapeNotVerified */
                __('Shop By') ?></strong>
        </div>
        <div class="block-content filter-content">
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?= /* @escapeNotVerified */
                    $block->getClearUrl() ?>" class="action clear filter-clear"><span><?= /* @escapeNotVerified */
                            __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>
            <?php $activeFilters = $block->getActiveFilters() ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $k => $filter): ?>
        <?php $attributeId = (!$block->isCategoryFilter($filter)) ? $filter->getData('attribute_model')->getAttributeId() : 0; ?>
        <?php if ($filter->getItemsCount()): ?>
        <?php if (!$wrapOptions): ?>
            <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= /* @escapeNotVerified */
                __('Shopping Options') ?></strong>
            <div class="filter-options" id="narrow-by-list" data-role="content"
                 data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": "<?php echo $activeFilters; ?>", "multipleCollapsible": true}}'>
                <?php $wrapOptions = true; ?>
                <?php endif; ?>
                <div data-role="collapsible" class="filter-options-item">
                    <?php $block->getChildBlock('renderer')->setAttributeId($filter) ?>
                    <div data-role="title" class="filter-options-title">
                        <?= /* @escapeNotVerified */ __($filter->getName()) ?></div>
                    <div id="attr_<?php echo $attributeId ?>" data-role="content"
                         class="filter-options-content"><?= /* @escapeNotVerified */
                        $block->getChildBlock('renderer')->render($filter) ?></div>
                </div>
                <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($wrapOptions): ?>
            </div>
        <?php else: ?>
            <script>
                require([
                    'jquery'
                ], function ($) {
                    $('#layered-filter-block').addClass('filter-no-options');

                });
            </script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
<div class="wp-ln-overlay"></div>
<div class="wp-ln-slider-js" data-mage-init='<?= /* @escapeNotVerified */ $block->getWidgetOptionsJson() ?>'>
    <script>
        <?php if ($jsClass): ?>
            require.config({
                map: {
                    '*': {
                        "productListToolbarForm": "<?= $jsClass?>"
                    }
                }
            });
        <?php endif; ?>

        require(['wpFilterSelect'], function(){
            wpFilterSelect.markSelected();
        });
    </script>

</div>



